# Generated by Django 5.2.8 on 2025-11-22 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('numero_tombo', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('em_manutencao', 'Em manutenção'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.localizacao')),
            ],
        ),
    ]
