# Generated by Django 5.2.8 on 2025-11-28 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('sala_aula', 'Sala de Aula'), ('laboratorio', 'Laboratório'), ('auditorio', 'Auditório'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('recursos', models.ManyToManyField(blank=True, to='patrimonios.patrimonio')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.espacofisico'),
        ),
        migrations.DeleteModel(
            name='Localizacao',
        ),
    ]
