# Generated by Django 5.2.8 on 2025-11-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0002_localizacao_alter_patrimonio_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
