# Generated by Django 5.2.8 on 2025-11-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0003_popular_localizacoes_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
