# Generated by Django 5.2.8 on 2025-11-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0003_alter_localizacao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='bloco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
