# Generated by Django 5.2.8 on 2025-12-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0004_localizacao_bloco_localizacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacao',
            name='tipo',
        ),
    ]
