# Generated by Django 5.2.8 on 2025-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0005_remove_localizacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='tipo',
            field=models.CharField(choices=[('Sala de Aula', 'Sala de Aula'), ('Laboratório', 'Laboratório'), ('Auditório', 'Auditório'), ('Sala de Professor / Projeto', 'Sala de Professor / Projeto'), ('Ginásio', 'Ginásio'), ('Sala Administrativa', 'Sala Administrativa'), ('Área Externa', 'Área Externa')], default='Sala de Aula', max_length=50),
        ),
    ]
