# Generated by Django 5.2.8 on 2025-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(blank=True, help_text='Nome completo do usuário', max_length=150, null=True),
        ),
    ]
