# Generated by Django 5.2.8 on 2025-11-12 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrimonios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='patrimonios.patrimonio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
