# Generated by Django 5.2.8 on 2025-11-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
