# Generated by Django 5.2.8 on 2025-11-22 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manutencoes', '0001_initial'),
        ('patrimonios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='patrimonio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='patrimonios.patrimonio'),
        ),
    ]
