# Generated by Django 5.2.8 on 2025-11-24 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutencao',
            options={'permissions': [('create_manutencao', 'Pode criar manutenção')]},
        ),
    ]
