# Generated by Django 5.2.8 on 2025-11-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0004_alter_manutencao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluido')], default='pendente', max_length=20),
        ),
    ]
