# Generated by Django 5.2.8 on 2025-11-22 02:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrimonios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('falta', 'Falta'), ('dano', 'Dano'), ('manutencao', 'Manutenção'), ('substituicao', 'Substituição')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('patrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.patrimonio')),
            ],
        ),
    ]
