# Generated by Django 5.2.8 on 2025-11-24 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'permissions': [('create_solicitacao', 'Pode criar solicitação'), ('approve_solicitacao', 'Pode aprovar solicitação')]},
        ),
    ]
