# Generated by Django 5.2.8 on 2025-11-12 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_solicitacao_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
