# Generated by Django 5.2.8 on 2025-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_alter_solicitacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em análise'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
