# Generated by Django 5.2.8 on 2025-12-10 03:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'ordering': ['-data_registro'], 'verbose_name': 'Histórico de Atividade', 'verbose_name_plural': 'Históricos de Atividades'},
        ),
        migrations.RemoveField(
            model_name='historico',
            name='data_atualizacao',
        ),
        migrations.AddField(
            model_name='historico',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='codigo',
            field=models.IntegerField(verbose_name='Código do Objeto'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='nome_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo de Atividade'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
