# Generated by Django 5.2.8 on 2025-12-10 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_alter_historico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitacao', 'Solicitação'), ('manutencao', 'Manutenção')], max_length=20)),
                ('item_id', models.IntegerField()),
                ('nome_item', models.CharField(max_length=255)),
                ('numero_tombo', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('data_abertura', models.DateTimeField()),
                ('data_atualizacao', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario_acao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_acoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
