# Generated by Django 5.2.8 on 2025-12-10 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_historicoatividade_delete_historico'),
        ('patrimonios', '0005_remove_localizacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoatividade',
            name='localizacao_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='patrimonios.localizacao'),
        ),
    ]
