# Generated by Django 5.2.8 on 2025-12-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0004_historicoatividade_localizacao_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoatividade',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
