# Generated by Django 5.2.8 on 2025-12-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0005_alter_historicoatividade_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoatividade',
            name='data_atualizacao',
            field=models.DateTimeField(),
        ),
    ]
